import Footer from "@/components/layouts/footer";
import NavBar from "@/components/layouts/navbar";
import { Providers } from "./GlobalRedux/provider";
import { ThemeProvider } from "@material-tailwind/react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />  
          {children}
          <Footer /> 
          </Providers>
      </body>
    </html>
  );
}
